#    - assert:
#        that:
#          - IP is match('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$')
#        fail_msg: Die Variable IP ist keine gültige IP-Adresse!
  
   
    - debug:    
        msg: "1. Meine Eingabe HN: {{HN}}"
    - debug:
        msg: "2. Meine Eingabe IP: {{IP}}"
    
    - name: install updates (Ubuntu, Debian)
      tags: update
      apt:
       upgrade: yes
       update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian', 'Linux Mint'] and inventory_hostname != 'networker.vreden.home'
          
    