---
- name: New Debian
  hosts: newbie_deb, dns
 # gather_facts: false
  
  vars_files:
    - roles/newone/host_vars/setup.yml
  
  vars_prompt:
    - name: IP
      prompt: Bitte IP-Adresse eingeben
      private: false
    
    - name: HN
      prompt: und hostname eingeben
      private: false
      
  roles:
     - newone
   
     
 
#command ohne tags: ansible-playbook --ask-become-pass --become-method su role_new.yml
