#    - assert:
#        that:
#          - IP is match('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$')
#        fail_msg: Die Variable IP ist keine gültige IP-Adresse!
  
   
    - debug:    
        msg: "Neu 1. Meine Eingabe HN: {{HN}}"
    - debug:
        msg: "Neu 2. Meine Eingabe IP: {{IP}}"
    
    
    - name: install updates (Ubuntu, Debian)
      tags: update
      apt:
       upgrade: yes
       update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian', 'Linux Mint'] and inventory_hostname != 'mywebserver.vreden.home'
          
    - name: install updates dist-upgrade
      tags: dist
      apt:
       upgrade: dist
       update_cache: yes
       autoremove: yes  # Remove obsolete packages
      when: ansible_distribution in ['Debian'] and inventory_hostname != 'mywebserver.vreden.home'
      
    - name: Upgrade all packages
      apt:
       upgrade: yes
       update_cache: yes
       autoremove: yes  # Remove obsolete packages
      when: ansible_distribution in ['Ubuntu'] and inventory_hostname != 'networker.vreden.home'
      
     
    - name: Setze statische IP-Adresse
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(\s*address\s)'
        line: 'address {{ IP }}'
      become: true
      when: ansible_distribution in ['Debian'] and inventory_hostname != 'networker.vreden.home'
      
    - name: Setze Subnetzmaske
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(\s*netmask\s)'
        line: 'netmask {{ netmask }}'
      become: true
      when: ansible_distribution in ['Debian'] and inventory_hostname != 'networker.vreden.home'
      
    - name: Setze Gateway
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(\s*gateway\s)'
        line: 'gateway {{ gateway }}'
      become: true
      when: ansible_distribution in ['Debian'] and inventory_hostname != 'networker.vreden.home'
      
    - name: Setze DNS-Server in /etc/network/interfaces
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^(\s*dns-nameservers\s)'
        line: 'dns-nameservers {{ dns_servers | join(" ") }}'
      become: true
      when: ansible_distribution in ['Debian'] and inventory_hostname != 'networker.vreden.home'
    
    - name: Set a hostname
      ansible.builtin.hostname:
        name: '{{ HN }}'
      become: true
      when: inventory_hostname != 'networker.vreden.home'
      
    - name: Resolv.conf-Vorlagendatei kopieren
      template:
        src: roles/newone/templates/resolv.conf.j2
        dest: /etc/resolv.conf
      notify:
        - Reboot
      when: inventory_hostname != 'networker.vreden.home'