# This is the network config written by 'subiquity'
network:
  ethernets:
    enp6s18:
      addresses:
      - 192.168.0.55/24
      nameservers:
        addresses:
        - 192.168.0.35
        search: []
      routes:
      - to: default
        via: 192.168.0.1
  version: 2
